# Generated by Django 5.2.8 on 2025-11-12 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operarios', to='incidencias.centro')),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('turno', models.CharField(max_length=50)),
                ('tipo_incidencia', models.CharField(blank=True, max_length=50)),
                ('modulo', models.CharField(blank=True, max_length=100)),
                ('estanque', models.CharField(blank=True, max_length=100)),
                ('parametros_afectados', models.CharField(blank=True, max_length=500)),
                ('oxigeno_nivel', models.CharField(blank=True, max_length=50)),
                ('oxigeno_valor', models.CharField(blank=True, max_length=50)),
                ('temperatura_nivel', models.CharField(blank=True, max_length=50)),
                ('temperatura_valor', models.CharField(blank=True, max_length=50)),
                ('conductividad_nivel', models.CharField(blank=True, max_length=50)),
                ('turbidez_nivel', models.CharField(blank=True, max_length=50)),
                ('turbidez_valor', models.CharField(blank=True, max_length=50)),
                ('sistema_sensor', models.CharField(blank=True, max_length=100)),
                ('sensor_detectado', models.CharField(blank=True, max_length=100)),
                ('sensor_nivel', models.CharField(blank=True, max_length=100)),
                ('sensor_valor', models.CharField(blank=True, max_length=50)),
                ('tiempo_resolucion', models.IntegerField(blank=True, null=True)),
                ('riesgo_peces', models.BooleanField(default=False)),
                ('perdida_economica', models.BooleanField(default=False)),
                ('riesgo_personas', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True)),
                ('tipo_incidencia_normalizada', models.CharField(blank=True, max_length=100)),
                ('centro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidencias.centro')),
                ('operario_contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidencias.operario')),
            ],
        ),
    ]
