# Generated by Django 5.2.8 on 2025-11-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0003_add_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centro',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
