# Generated by Django 5.2.8 on 2026-01-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0007_sensorconfig_monitoreosensores'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='contacto_proveedor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='plataforma',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='razon_caida',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='sistema_fallando',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='tiempo_fuera_servicio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
