# Generated by Django 5.2.8 on 2026-01-28 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0008_incidencia_contacto_proveedor_incidencia_plataforma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportePlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('turno', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=20)),
                ('plataforma', models.CharField(choices=[('INNOVEX', 'INNOVEX'), ('SINPLANT', 'SINPLANT')], max_length=20)),
                ('sistema_fallando', models.CharField(max_length=200)),
                ('tiempo_fuera_servicio', models.IntegerField(help_text='Tiempo en minutos')),
                ('contacto_proveedor', models.BooleanField(default=False)),
                ('razon_caida', models.TextField()),
                ('riesgo_peces', models.BooleanField(default=False)),
                ('perdida_economica', models.BooleanField(default=False)),
                ('responsable', models.CharField(max_length=200)),
                ('observacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_plataforma', to='incidencias.centro')),
            ],
            options={
                'verbose_name': 'Reporte de Plataforma',
                'verbose_name_plural': 'Reportes de Plataformas',
                'ordering': ['-fecha_hora', '-creado_en'],
            },
        ),
    ]
