# Generated by Django 5.2.8 on 2026-01-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0009_reporteplataforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteplataforma',
            name='contacto_proveedor',
            field=models.CharField(choices=[('no', 'No se contactó'), ('si', 'Sí, con respuesta'), ('sin_respuesta', 'Sí, sin respuesta')], default='no', max_length=20),
        ),
    ]
