# Generated by Django 5.2.8 on 2026-01-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0010_alter_reporteplataforma_contacto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoreosensores',
            name='hora_inicio',
            field=models.TimeField(blank=True, help_text='Hora de inicio de la incidencia', null=True),
        ),
    ]
