# Generated by Django 5.2.8 on 2026-01-29 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0012_seed_centros_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoreosensores',
            name='operario_contacto',
            field=models.ForeignKey(blank=True, help_text='Operario que respondió', null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidencias.operario'),
        ),
    ]
