# Generated by Django 5.2.8 on 2026-01-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0013_monitoreosensores_operario_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoreosensores',
            name='operario_contacto',
        ),
        migrations.AlterField(
            model_name='reporteplataforma',
            name='plataforma',
            field=models.CharField(choices=[('INNOVEX', 'INNOVEX'), ('SINPLANT', 'SINPLANT'), ('IDEAL CONTROL', 'IDEAL CONTROL')], max_length=20),
        ),
    ]
