# Generated by Django 5.2.8 on 2026-01-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0014_remove_monitoreosensores_operario_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteplataforma',
            name='unidad_tiempo',
            field=models.CharField(choices=[('minutos', 'Minutos'), ('dias', 'Días')], default='minutos', max_length=10),
        ),
        migrations.AlterField(
            model_name='reporteplataforma',
            name='tiempo_fuera_servicio',
            field=models.IntegerField(help_text='Duración del tiempo fuera de servicio'),
        ),
    ]
